Improve the CLI auth logic
pksunkara/octonode pull request #226
Opened 2016-02-03 10:02 UTC by ankon

These are changes I needed for creating a desktop application using this library:

1. Provide `client_id`, `client_secret`, `note`, `note_url`, and `fingerprint` in the authorization request
2. Allow reusing an existing authorization 

There is still one open issue here: github will return a hashed token and the last 8 characters when reusing a token, but these values are not provided to the callback, so the app cannot actually verify the token. I'll open a separate issue for that, as it might need incompatible changes to the API.

2016-02-03 17:59 UTC, pksunkara commented on src/octonode/auth.coffee
> +          note_url: @options.note_url
Please add the above 5 properties only if they exist in `@options`.

2016-02-03 18:00 UTC, pksunkara commented on src/octonode/auth.coffee
> +          if res.statusCode in [200, 201] then callback(null, body.id, body.token) else callback(new Error(body.message))
Also, please use a variable for this similar to how you setup `authorizationUrl`.

```coffee
if res.statusCode is statusCode then ...
```

2016-02-03 18:01 UTC, pksunkara commented
Just a few comments which need to be addressed.

2016-11-04 10:15 UTC, pksunkara commented
@ankon Any update on this?

2017-03-03 20:14 UTC, pksunkara commented
@ankon Could you give an update on this?

2017-05-08 10:07 UTC, odykyi requested changes

2017-05-08 10:07 UTC, odykyi commented on lib/octonode/auth.js
> +          body: JSON.stringify({
pls use `json: true` instead of JSON.stringify
ex.
   ```
    
          body: {
             scopes: scopes,
             client_id: this.options.id,
             client_secret: this.options.secret,
             fingerprint: this.options.fingerprint,
             note: this.options.note,
             note_url: this.options.note_url
          },
          json: true
```

2017-05-08 10:07 UTC, odykyi commented on lib/octonode/auth.js
> +            if ((ref = res.statusCode) === 200 || ref === 201) {
pls dont assign variable in `if ` statement
its implicit

2017-05-19 12:21 UTC, ankon commented
Oops, missed this.  :/

I'm no longer using this library, so right now can not do any updates.

2019-03-21 03:35 UTC, Aboodi19900 approved these changes

2019-03-21 03:36 UTC, Aboodi19900 requested changes
Aboodi19900@hotmail.com

2024-08-23 11:27 UTC, closed without merging